//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryItems()
        {
            this.RecommandPurchaseItems = new HashSet<RecommandPurchaseItems>();
        }
    
        public int itemSerialNum { get; set; }
        public string itemName { get; set; }
        public string itemDescription { get; set; }
        public Nullable<int> itemAmount { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string itemPicture { get; set; }
        public Nullable<int> eventSerialNum { get; set; }
        public Nullable<int> offerSerialNum { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual GreenEvents GreenEvents { get; set; }
        public virtual PriceOffer PriceOffer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecommandPurchaseItems> RecommandPurchaseItems { get; set; }
    }
}
