//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class igroup196DbContext1 : DbContext
    {
        public igroup196DbContext1()
            : base("name=igroup196DbContext1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeePosition> EmployeePosition { get; set; }
        public virtual DbSet<GreenConstraints> GreenConstraints { get; set; }
        public virtual DbSet<GreenEvents> GreenEvents { get; set; }
        public virtual DbSet<InventoryCategories> InventoryCategories { get; set; }
        public virtual DbSet<InventoryItems> InventoryItems { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<PriceOffer> PriceOffer { get; set; }
        public virtual DbSet<RecommandPurchaseItems> RecommandPurchaseItems { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VehicleList> VehicleList { get; set; }
        public virtual DbSet<VehicleMaintenance> VehicleMaintenance { get; set; }
    }
}
