//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int businessNumber { get; set; }
        public string companyAddress { get; set; }
        public string companyEmail { get; set; }
        public string repName { get; set; }
        public string repLastName { get; set; }
        public string repEmailAddress { get; set; }
        public Nullable<System.DateTime> StartWorkDate { get; set; }
        public Nullable<bool> isSupplierActive { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
