//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleList()
        {
            this.VehicleMaintenance = new HashSet<VehicleMaintenance>();
        }
    
        public int licensePlateNum { get; set; }
        public string vehicleType { get; set; }
        public string vehicleColor { get; set; }
        public string licenseType { get; set; }
        public string vehicleOwnership { get; set; }
        public string manufacturingYear { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> eventSerialNum { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual GreenEvents GreenEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleMaintenance> VehicleMaintenance { get; set; }
    }
}
