//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleMaintenance
    {
        public int maintenance_id { get; set; }
        public Nullable<System.DateTime> maintenance_date { get; set; }
        public string maintenance_description { get; set; }
        public string garageName { get; set; }
        public Nullable<int> vehicle_id_fk { get; set; }
    
        public virtual VehicleList VehicleList { get; set; }
    }
}
